name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.8 ]
        poetry-version: [ 1.1.6 ]
        os: [ ubuntu-18.04 ]
    runs-on: ubuntu-18.04
    steps:
      - uses: huaxk/postgis-action@v1
        with:
          postgresql version: '11'
          postgresql password: 'wc-guide-backend'
          postgresql user: 'guide'
          postgresql db: 'wc-guide-backend-db'
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install GDAL
        command: |
          sudo apt update
          sudo apt install -y gdal-bin
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        run: poetry run python -m pytest